export const HardSkills = [
	// Tenho grande conhecimento e experiencia
	{ skill: "Web-Structure.png", skillName: "" },
	{ skill: "Figma.png", skillName: "" },
	{ skill: "UI-&-UX.png", skillName: "" },
	{ skill: "Portugol-Studio.png", skillName: "" },
	{ skill: "C.png", skillName: "" },
	{ skill: "Cpp.png", skillName: "C++" },
	{ skill: "PyCharm.png", skillName: "" },
	{ skill: "Python.png", skillName: "" },
	{ skill: "Visual-Studio-Code.webp", skillName: "VS Code" },
	{ skill: "HTML.webp", skillName: "" },
	{ skill: "CSS.png", skillName: "" },
	{ skill: "SASS.png", skillName: "" },
	{ skill: "Bootstrap.png", skillName: "" },
	{ skill: "Tailwind.png", skillName: "" },
	{ skill: "Java-Script.webp", skillName: "" },
	{ skill: "AJAX.png", skillName: "" },
	{ skill: "jQuery.png", skillName: "" },
	{ skill: "TypeScript.png", skillName: "" },
	{ skill: "Git.png", skillName: "" },
	{ skill: "GitHub.png", skillName: "" },
	{ skill: "MVC.png", skillName: "" },
	{ skill: "XAMP.png", skillName: "" },
	{ skill: "PHP.png", skillName: "" },
	{ skill: "UML-&-OOP.png", skillName: "" },
	{ skill: "Java.png", skillName: "" },
	{ skill: "Cs.png", skillName: "C#" },
	{ skill: "NetBeans.png", skillName: "" },
	{ skill: "MySQL.png", skillName: "" },
	{ skill: "Workbench.png", skillName: "" },
	{ skill: "FireBird.png", skillName: "" },
	{ skill: "Laravel.png", skillName: "" },
	{ skill: "Firebase.png", skillName: "" },
	{ skill: "Node-Js.png", skillName: "" },
	{ skill: "Rest-API.png", skillName: "" },
	{ skill: "Prisma.png", skillName: "" },
	{ skill: "ESLint.png", skillName: "" },
	{ skill: "SQLite.png", skillName: "" },
	{ skill: "React.png", skillName: "" },
	{ skill: "PostgreSQL.png", skillName: "" },
	{ skill: "MongoDB.png", skillName: "" },
	{ skill: "Next-JS.png", skillName: "" },
	{ skill: "Vercel.png", skillName: "" },
	{ skill: "Scrum.png", skillName: "" },
	{ skill: "Cisco-Packet-Tracer.webp", skillName: "" },
	{ skill: "Linux.png", skillName: "" },
	{ skill: "Windows.png", skillName: "" },
	{ skill: "Aseprite.png", skillName: "" },
	{ skill: "Game-Maker.png", skillName: "" },
	{ skill: "RPG-Maker.png", skillName: "" },
	{ skill: "Brave.png", skillName: "" },
	{ skill: "Chrome.png", skillName: "" },


	// So vi o basico de como se usa nunca apliquei na pratica
	// { skill: "Arduino.png", skillName: "" },
	// { skill: "DotNET.png", skillName: ".NET" },
	// { skill: "WordPress.png", skillName: "" },
	// { skill: "Godot.png", skillName: "" },
	// { skill: "Pacote-Office.png", skillName: "" },
	// { skill: "Visual-Studio.png", skillName: "" },
	// { skill: "Ruby.png", skillName: "" },
	// { skill: "Docker.webp", skillName: "" },
	// { skill: "Vue-JS.png", skillName: "" },
	// { skill: "Slim.png", skillName: "" },
	// { skill: "Ionic.png", skillName: "" },
	// { skill: "Android-Studio.png", skillName: "" },
	// { skill: "Angular.png", skillName: "" },

];